#!/bin/busybox sh
/bin/busybox --install -s
shell(){
  setsid sh -c 'exec sh </dev/tty1 >/dev/tty1 2>&1'
}
clear_line(){
  printf "\r                                                                                                                      \r\
    \033[1A\
    \r                                                                                                                      \r"
}
failure(){
  echo "Error Code" $1
  echo "Restarting in 30s"
  sleep 30
  reboot -f
}
restart(){
  echo "Rebooting"
  sleep 5
  reboot -f
}
are_you_sure(){
  while :
  do
    echo "This will erase the current system. Are you sure? (y/n)"
    read -n1 -s answer     
    case $answer in
      y)
        break
      ;; 
      n) 
        restart
      ;;
    esac
    clear_line
  done
}
reinstall(){
  echo "Clearing the Disk"
  # magic. we dont have to run bcdboot to get windows to boot if we recycle old UUIDs...
  sgdisk --zap-all \
    --new 1::+100M --typecode=1:ef00 --change-name=1:'EFI System Partition' -u 1:"25A4322D-77E1-4920-839F-8DF27BD5CF10" \
    --new 2::-0 --typecode=2:0700 --change-name=2:'Windows' -u 2:"8F2A36E4-15C0-46BC-B36F-DDB8225A910B" \
    /dev/sda &> /dev/null || failure 00
  sgdisk -U "F83E19B8-A267-4076-A13A-3FD2E6478A6C" /dev/sda &> /dev/null || failure 01
  mkfs.vfat -F32 /dev/sda1 || failure 02
  mkfs.ntfs -Q /dev/sda2 &> /dev/null || failure 03
  wimlib-imagex apply /mnt/nfs/images/current.esd 1 /dev/sda2 || failure 04
  echo "Mounting New System"
  mount /dev/sda1 /mnt/efi || failure 05
  ntfs-3g /dev/sda2 /mnt/ntfs || failure 06
  echo "Installing UEFI Boot Files"
  tar -xJf /mnt/nfs/images/efi/efi.tar.xz -C /mnt/efi || failure 07
  if [ ! -d /sys/firmware/efi ]; then
    # straight-up magical
    echo "Installing BIOS to UEFI Adapter"
    dd if=/mnt/nfs/images/efi/boot0af of=/dev/sda bs=440 count=1 conv=notrunc &> /dev/null || failure 07
    dd if=/dev/sda1 bs=512 count=1 of=part_mbr_orig &> /dev/null || failure 08
    cp /mnt/nfs/images/efi/boot1f32 part_mbr_new || failure 09
    dd if=part_mbr_orig of=part_mbr_new skip=3 seek=3 bs=1 count=87 conv=notrunc &> /dev/null || failure 10
    dd if=part_mbr_new of=/dev/sda1 bs=512 count=1 conv=notrunc &> /dev/null || failure 11
    cp /mnt/nfs/images/efi/boot7 /mnt/efi/boot || failure 12
    mkdir -p /mnt/efi/EFI/CLOVER || failure 13
    mv /mnt/efi/EFI/Boot/bootx64.efi /mnt/efi/EFI/CLOVER/CLOVERX64.efi || failure 14
  fi
  if [ -f /mnt/nfs/images/unattend.xml ]; then
    echo "Installing Unattended Script"
    mkdir -p /mnt/ntfs/Windows/Panther/Unattend || failure 15
    cp /mnt/nfs/images/unattend.xml /mnt/ntfs/Windows/Panther/Unattend/ || failure 16
  fi
  if [ -f /mnt/nfs/images/img.jpg ]; then
    mkdir -p /mnt/ntfs/Windows/System32/oobe/info/backgrounds/ || failure 17
    cp /mnt/nfs/images/img.jpg /mnt/ntfs/Windows/System32/oobe/info/backgrounds/backgroundDefault.jpg || failure 18
  fi
  echo "Cleaning up and Unmounting"
  sync
  umount /mnt/ntfs || failure 19
  umount /mnt/efi || failure 20
}
echo "Mounting System"
mount -t devtmpfs none /dev || failure 21
mount -t proc none /proc || failure 22
mount -t sysfs none /sys || failure 23
echo "Configuring Network"
ifconfig eth0 up || failure 24
udhcpc -t 10 -q -s /bin/simple.script &> /dev/null || failure 25
echo "Mounting NFS Drive"
# find a magic way to use dhcp options here instead of hardcoding thx
mount -t nfs4 192.168.1.140:/ /mnt/nfs || failure 26
# we could bust this script and binaries out of the kernel at this point, and run them from nfs, but what the heck
while :
do
  echo "Would you like to (r)einstall Windows, (b)ackup user files and reinstall Windows, or (c)apture a Windows installation?"
  read -n1 -s answer
  case $answer in
    r)
      clear_line
      echo "Reinstalling Windows"
      are_you_sure
      clear_line
      reinstall
      break
    ;;
    b)
      clear_line
      echo "Backing Up User Files and Reinstalling Windows"
      are_you_sure
      clear_line
      echo "Capturing User Files"
      ntfs-3g /dev/sda2 /mnt/ntfs || failure 27
      wimlib-imagex capture /mnt/ntfs/Users /mnt/nfs/capture/users.wim --compress=fast --chunk-size=64K || failure 28
      umount /mnt/ntfs || failure 29
      reinstall
      echo "Copying User Files to the New System"
      ntfs-3g /dev/sda2 /mnt/ntfs || failure 30
      wimlib-imagex apply /mnt/nfs/capture/users.wim 1 /mnt/ntfs/Users || failure 31
      sync
      umount /mnt/ntfs || failure 32
      rm /mnt/nfs/capture/users.wim || failure 33
      break
    ;;
    c)
      clear_line
      echo "Capturing Windows Install"
      wimlib-imagex capture /dev/sda2 /mnt/nfs/capture/current.esd "Windows 10" --solid --solid-compress=LZMS:100 --solid-chunk-size=512M --threads=1 || failure 34
      break
    ;;
    s)
      shell
    ;;
  esac
  clear_line
done
restart
